#!/usr/bin/env bash

# collection of useful bash aliases and functions

alias lola='git log --graph --decorate --pretty=oneline --abbrev-commit --all'
# brew install coreutils for this one
alias l='gls --color -lhF --group-directories-first'
alias lt='du -sh * | sort -h'
alias lth='du -sh * .* | sort -h' # can be broken, if there are no hidden files
# but better just to use ncdu, it's much nicer and faster

alias count='find . -type f | wc -l'
alias startgit='cd `git rev-parse --show-toplevel` && git checkout master && git pull'

# from https://opensource.com/article/19/7/bash-aliases
function cl() {
    DIR="$*";
	# if no DIR given, go home
	if [ $# -lt 1 ]; then 
		DIR=$HOME;
    fi;
    builtin cd "${DIR}" && \
    # use your preferred ls command
    l
	# ls -F --color=auto
}

alias ve='. .venv/bin/activate'
alias de='deactivate'

